[project]
name = "milenium"
version = "1.5.0"
description = "OSINT aggregator"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "VexxDev200"}]
dependencies = [
    "requests",
    "aiohttp",
    "dnspython",
    "phonenumbers",
    "beautifulsoup4",
    "rich",
    "click",
    "python-whois",
    "psycopg2-binary",
    "maigret",
    "sherlock-project",
    "holehe",
    "telethon",
    "PicImageSearch",
    "aiogram>=3.0",
]

[project.scripts]
milenium = "milenium.cli:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["milenium*"]